### ISSUE TITLE
Subscriptions rerun each 10 seconds

### ISSUE THREAD

**Issue by dpatte** [peerlibrary/meteor-reactive-publish#11]
I am seeing a strange issue. 

I am actually publishing Meteor.user account data, so that user data is accessible to an admin. 

On my development machine, this app is running correctly.

But when I deploy, it reruns subscriptions every 10 seconds. I only call subscribe in a single place, in the default waitOn of IronRouter. It should rerun only if the userId changes. When I login the waiton waits for subscription calls. I then expect it to be done. 

But it runs again in 10 seconds, and again, and again - but only when its deployed.

Any ideas?

Also is reactive-publish driven by a 10 second timer?

Thanks

**Comment by mitar** [comment]
This sounds like something connected with polling instead of oplog? Polling is every 10 seconds? Do you have oplog enabled on production?

Can you share some code?

Also, rerunning on userId change is something done already. Do you need to use autorun?

**Comment by dpatte** [comment]
I suspected polling but i have been told that my deployed system is actually using oplog.

Changing userId changes the list of users whose data I want to publish. I actually then publish more detailed data about each user, as well as their docs.

**Comment by mitar** [comment]
Can you show some code?

**Comment by dpatte** [comment]
It turns out that the deployed system is using polling after all. So, yes it has to do with polling.
I have also discovered that it also only occurs on pages that have Router.onBeforeAction(requireLoginRt, .....
I'm now beginning to think it is a router issue, or a conflict between iron router and reactive publish, or related to polling's lazy comparison of record changes.

**Comment by mitar** [comment]
Can you create a small reproduction?

**Comment by dpatte** [comment]
Actually, I removed the autorun, and I still have the issue. I guess the problem is somewhere else. Thanks for putting up with my questions.

**Comment by etyp** [comment]
@mitar I'm a bit confused here - it seems like any `find` done within an autorun (excluding the cursor which is returned) uses the polling observe driver.

For example, if I have:

```
Meteor.publish('messagesForGroup', function (groupId) {
  this.autorun(() => {
    const group = Groups.findOne(groupId, { fields: { members: 1 } });
    if (group.members.indexOf(this.userId) > -1) {
      return Messages.find({ group: group._id });
    }
  });
});
```

It seems like the findOne `Groups.findOne(groupId, { fields: { members: 1 } });` uses polling instead of oplog.

Is that expected?

**Comment by etyp** [comment]
From what I can tell, the [reactive-mongo package adds](https://github.com/peerlibrary/meteor-reactive-mongo/blob/master/server.coffee#L49) `addedBefore` and `movedBefore` callbacks to `fetch`, `map` and `forEach` on cursors.

Because of this, it fails the first check in `observeChanges` in Meteor's [mongo_driver.js](https://github.com/meteor/meteor/blob/d8042c8fa9dd0cc53604b2729ac33333a2ce5b73/packages/mongo/mongo_driver.js#L1291) for whether or not it can use oplog.

The presence of `addedBefore` and `movedBefore` means that `ordered` returns true when the driver calls [LocalCollection._observeChangesCallbacksAreOrdered](https://github.com/meteor/meteor/blob/24865b28a0689de8b4949fb69ea1f95da647cd7a/packages/minimongo/local_collection.js#L1361).

Was it ever intended for finds inside of server-side autoruns to use oplog or are they always expected to fall back on polling?

**Comment by mitar** [comment]
I think a new issue would be better instead of commenting on and old one.

But this is a great catch! No, this was not expected. I have copied this from the client side code, which does not have this restriction. Maybe open an issue in reactive-mongo package and we can work through it there?
