### ISSUE TITLE
reactive-publish & publish-counts error: no method 'getCollectionView' (server-side rendering)

### ISSUE THREAD

**Issue by SachaG** [peerlibrary/meteor-reactive-publish#17]
I'm calling `Counts.publish()` from the [publish counts](https://github.com/percolatestudio/publish-counts) package within a server-side autorun, and it sometimes triggers the following error:

```
 Exception from Tracker recompute function:
 TypeError: Object [object Object] has no method 'getCollectionView'
     at PublishContext.publish.added (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:291:1)
     at Object.Counts.publish (packages/tmeasday_publish-counts/server/publish-counts.js:79:1)
     at PublishContext.<anonymous> (packages/nova:posts/lib/server/publications.js:79:12)
     at Computation.<anonymous> (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:313:1)
     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
     at packages/meteor/dynamics_nodejs.js:123:1
     at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:446:1
     at packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:424:1
     at Function.FiberUtils.synchronize (packages/peerlibrary_fiber-utils/packages/peerlibrary_fiber-utils.js:163:1)
     at Computation.Tracker.Computation.Computation._runInside (packages/peerlibrary_server-autorun/packages/peerlibrary_server-autorun.js:413:1)
```

Here's the relevant publication code: https://github.com/TelescopeJS/Telescope/blob/devel/packages/nova-posts/lib/server/publications.js#L71-L91

**Comment by SachaG** [comment]
By the way, the publish-counts package uses a client-only "local" collection, I don't know if that has anything to do with it?

Here's a log of the `@_session` object when this happens:

```
 { id: 'yo5gG2F2QdpapDyiG',
  userId: undefined,
  inQueue: {},
  connectionHandle:
   { id: 'yo5gG2F2QdpapDyiG',
     close: [Function],
     onClose: [Function],
     clientAddress: '127.0.0.1',
     httpHeaders:
      { host: 'meta.telescopeapp.org',
        connection: 'Keep-alive',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        from: 'googlebot(at)googlebot.com',
        'user-agent': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
        'accept-encoding': 'gzip,deflate,br',
        'if-modified-since': 'Tue, 07 Jun 2016 01:35:25 UTC' } },
  added: [Function],
  changed: [Function],
  removed: [Function],
  sendReady: [Function] }
```

**Comment by mitar** [comment]
The reason why you are experiencing this is because you are using fast-render. See that `_session` object looks like [mock session object](https://github.com/kadirahq/fast-render/blob/master/lib/server/publish_context.js#L6). I [have made some modifications in the past](https://github.com/kadirahq/fast-render/commits/master/lib/server/publish_context.js) to make the context as close as possible to the real context, but it is not yet perfect.

See my comments here:
- https://github.com/kadirahq/fast-render/issues/159
- https://github.com/kadirahq/fast-render/pull/160#issuecomment-189819229 (I comment how this is still not perfect)

So this issue you are having is lack of support for fast-render.

**Comment by mitar** [comment]
Server side is not supported for now.
